services:
  instagram_api:
    image: tajievolimjon/instagram_api
    container_name: instagram_api
    restart: always
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - images:/app/wwwroot/images
    depends_on:
      - instagram_db
    networks:
      - instagram-dev

  instagram_db:
    image: postgres:16.4-bullseye
    container_name: instagram_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=instagram2024root
    ports:
      - "5403:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - instagram-dev

networks:
  instagram-dev:
    driver: bridge

volumes:
  postgresql-data:
  images: